---
- name: Configure web server
  hosts: webserver
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Install dig
      ansible.builtin.apt:
        name: dnsutils
        state: present
    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
